### ISSUE TITLE
config.yaml Rules are not fetching all attributes metrics when using selective Object for Mbean

### ISSUE THREAD

**Issue by KMTahir** [prometheus/jmx_exporter#1020]
Hi,
I am trying to get the tomcat JVM metrics using Java Agent jmx_prometheus_javaagent ( have tried 0.20.0 and 1.0.1 both version )

 My issue is that if I use * in Rule file like below

```
rules:
- pattern: ".*"

```
It work properly and fetch all attribute etc. But I want to get specfic Mbeans only ( Memory , Threading,Garbagecollection and ClassLoading ). I am using the below configuration for it

```
rules:
- pattern: "java.lang:type=Memory"
- pattern: "java.lang:type=Threading"
- pattern: "java.lang:type=GarbageCollector,name=(.*)"
- pattern: "java.lang:type=ClassLoading"
```

while using above config. it is not fetching many attribute which are part of these Mbeans.   Like java_lang_ClassLoading_LoadedClassCount is atttribute of  ojbect ClassLoading  but it is not receiving.

Similarly their are some other attributes which are missing if I don't use  ".*"  in config.yaml file

am I  missing something or its a bug of jmx_prometheus_javaagent ?

Just for info, I am verifying the list of metrics like below

`curl localhost:9093/metrics`

**Comment by dhoard** [comment]
@KMTahir try these rules...

```
rules:
  - pattern: "java.lang<type=Memory(.*)><(.*)>"
  - pattern: "java.lang<type=Threading(.*)><(.*)>"
  - pattern: "java.lang<type=GarbageCollector(.*)><(.*)>"
  - pattern: "java.lang<type=ClassLoading(.*)><(.*)>"
```
