### ISSUE TITLE
metricCustomizers / extraMetrics doesn't skips an MBean with string attributes only

### ISSUE THREAD

**Issue by polarnik** [prometheus/jmx_exporter#1147]
# Description

I have an MBean with two attributes, but both attributes are strings. I would like to customize a config file and convert two string attributes to labels with adding an extra-Metric via the option extraMetrics

Prometheus Exporter skips MBeans without numeric attributes.  We can try to add a numeric attribute via the 
metricCustomizers / extraMetrics
see an example: https://github.com/prometheus/jmx_exporter/blob/01700b2edc50e927a7089ad34057915629e0e77a/integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test/core/MetricCustomizersAttributesAsLabelsExtraMetricsTest/JavaAgent/exporter.yaml#L9

But the output will skip the MBean anyway

# Environment

- Java 21
- jmx-exporter (main) commit f024c74d83aea4beb8531d661e38356e37dcb781
- youtrack docker container jetbrains/youtrack:2025.1.62967

# Config 
## jmx_exporter.yml

```yaml
startDelaySeconds: 10
lowercaseOutputName: false
lowercaseOutputLabelNames: false

includeObjectNames: ["jetbrains.youtrack:type=Maintenance,name=Global"]
metricCustomizers:
  - mbeanFilter:
      domain: jetbrains.youtrack
      properties:
        type: Maintenance
        name: Global
    attributesAsLabels:
      - Build
      - Version
    extraMetrics:
      - name: isActive
        value: true
        description: This is a boolean value indicating if the scenario is still active or is completed.
 ```

## youtrack.jvmoptions

```yaml
-XX:NativeMemoryTracking=summary
-XX:+PrintFlagsFinal
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.port=9010
-Dcom.sun.management.jmxremote.rmi.port=9011
-Dcom.sun.management.jmxremote.local.only=false
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Djava.rmi.server.hostname=127.0.0.1

-javaagent:/opt/app/jmx_prometheus_javaagent-1.1.0-post.jar=youtrack:9404:/opt/app/jmx_exporter.yml
```

## docker-compose

```yaml
services:
  youtrack:
    image: jetbrains/youtrack:2025.1.62967
    hostname: youtrack
    restart: "no"
    ports:
      - '9404:9404'
      - '9010:9010'
      - '9011:9011'
      - "8080:8080"
    tmpfs:
      /tmp
    volumes:
      - ./volumes/youtrack_data:/opt/youtrack/data
      - ./volumes/youtrack_conf:/opt/youtrack/conf
      - ./volumes/youtrack_logs:/opt/youtrack/logs
      - ./volumes/youtrack_backups:/opt/youtrack/backups
      - ./volumes/youtrack_temp:/opt/youtrack/temp
      - "./configs/youtrack/youtrack.jvmoptions:/opt/youtrack/conf/youtrack.jvmoptions:ro"
      - "./configs/prometheus_jmx_exporter/jmx_exporter.yml:/opt/app/jmx_exporter.yml:ro"
      - "./tools/jmx_prometheus_javaagent-1.1.0-post.jar:/opt/app/jmx_prometheus_javaagent-1.1.0-post.jar:ro"
```

# Steps

1. Start a docker-compose
2. Copy a wizard_token from the docker logs
3. Open http://127.0.0.1:8080/
4. Add the wizard_token from the logs: http://127.0.0.1:8080/?wizard_token=pk191NZmHm8GGTOfpdVy
5. Start creating a new instance
6. Set a domain:
  - http://127.0.0.1:8080
7. Set a password and tokens
  - admin
  - admin
8. Wait a few seconds
9. Install visualVM https://visualvm.github.io/
10. Install a visualVM plugin: Menu / Tools / Plugins / Available Plugins / **VisualVM MBean**
11. Connect from the VisualVM tool to the remote host: 127.0.0.1:9010
12. Open an MBean with numeric and String attributes, for example jetbrains.youtrack:type=Hub,name=HubIntegration

# Actual result

A test MBean is:

- jetbrains.youtrack:type=Maintenance,name=Global

Attributes:

| Attribute name | Readable | Type | Value |
| --- | --- | --- | --- |
| Build | true | java.lang.String | 62967 |
| Version | true | java.lang.String | 2025.1 |

<img width="1243" alt="Image" src="https://github.com/user-attachments/assets/64b4ecfb-32dc-432f-9b52-ac3ca65251d3" />

<img width="1243" alt="Image" src="https://github.com/user-attachments/assets/bd6782d7-5cff-4895-a506-36b8df3f8aae" />

An output doesn't have the metric **isActive**

# Expected result

The output will have a metric **isActive**

# Workaround

We can create metrics for each string attribute via the config:

```yaml
startDelaySeconds: 10
lowercaseOutputName: false
lowercaseOutputLabelNames: false

whitelistObjectNames:
  - "jetbrains.youtrack:type=Maintenance,name=Global"

rules:
  - pattern: 'jetbrains.youtrack<type=Maintenance, name=Global><>(\w+): (.+)'
    name: youtrack_version_info
    labels:
      $1: $2
    value: 1.0
    type: GAUGE
    help: Application version info
```

And merge a few metrics into one via Grafana dashboard transformations

<img width="1228" alt="Image" src="https://github.com/user-attachments/assets/5329ab24-91b9-409f-b067-290074f0ee0c" />
