### ISSUE TITLE
30+ mins HTTP response time using remote JMX host

### ISSUE THREAD

**Issue by agolomoodysaada** [prometheus/jmx_exporter#159]
Releases Tested: `0.9` and `0.7`

I'm trying to setup jmx_exporter with a remote host exposing jmx metrics. I can already access JMX metrics using `jconsole` without any issues. However, using the below configuration doesn't return any http responses when hitting `localhost:5556/metrics` and keeps spinning forever. I do see some verbose logs showing up when I hit the endpoint.

What am I doing wrong?

Docker compose
```yml
  jmx_exporter:
    image: java:8-alpine
    command: java -verbose -jar /opt/jmx_exporter/jmx_exporter.jar 5556 /opt/jmx_exporter/config.yml
    ports:
      - '5556:5556'
    volumes:
      - './jmx_prometheus_httpserver-0.9-jar-with-dependencies.jar:/opt/jmx_exporter/jmx_exporter.jar'
      - './kafka-jmx-config.yml:/opt/jmx_exporter/config.yml'
```

Kafka config file based on sample config
```yml
hostPort: <MY_REMOTE_HOST>:<MY_REMOTE_PORT>
ssl: false
lowercaseOutputName: true
startDelaySecs: 0
rules:
  - pattern : kafka.cluster<type=(.+), name=(.+), topic=(.+), partition=(.+)><>Value
    name: kafka_cluster_$1_$2
    labels:
      topic: "$3"
      partition: "$4"
  - pattern : kafka.log<type=Log, name=(.+), topic=(.+), partition=(.+)><>Value
    name: kafka_log_$1
    labels:
      topic: "$2"
      partition: "$3"
  - pattern : kafka.controller<type=(.+), name=(.+)><>(Count|Value)
    name: kafka_controller_$1_$2
  - pattern : kafka.network<type=(.+), name=(.+)><>Value
    name: kafka_network_$1_$2
  - pattern : kafka.network<type=(.+), name=(.+)PerSec, request=(.+)><>Count
    name: kafka_network_$1_$2_total
    labels:
      request: "$3"
  - pattern : kafka.network<type=(.+), name=(\w+), networkProcessor=(.+)><>Count
    name: kafka_network_$1_$2
    labels:
      request: "$3"
    type: COUNTER
  - pattern : kafka.network<type=(.+), name=(\w+), request=(\w+)><>Count
    name: kafka_network_$1_$2
    labels:
      request: "$3"
  - pattern : kafka.network<type=(.+), name=(\w+)><>Count
    name: kafka_network_$1_$2
  - pattern : kafka.server<type=(.+), name=(.+)PerSec\w*, topic=(.+)><>Count
    name: kafka_server_$1_$2_total
    labels:
      topic: "$3"
  - pattern : kafka.server<type=(.+), name=(.+)PerSec\w*><>Count
    name: kafka_server_$1_$2_total
    type: COUNTER

  - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>(Count|Value)
    name: kafka_server_$1_$2
    labels:
      clientId: "$3"
      topic: "$4"
      partition: "$5"
  - pattern : kafka.server<type=(.+), name=(.+), topic=(.+), partition=(.*)><>(Count|Value)
    name: kafka_server_$1_$2
    labels:
      topic: "$3"
      partition: "$4"
  - pattern : kafka.server<type=(.+), name=(.+), topic=(.+)><>(Count|Value)
    name: kafka_server_$1_$2
    labels:
      topic: "$3"
    type: COUNTER

  - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>(Count|Value)
    name: kafka_server_$1_$2
    labels:
      clientId: "$3"
      broker: "$4:$5"
  - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+)><>(Count|Value)
    name: kafka_server_$1_$2
    labels:
      clientId: "$3"
  - pattern : kafka.server<type=(.+), name=(.+)><>(Count|Value)
    name: kafka_server_$1_$2

  - pattern : kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count
    name: kafka_$1_$2_$3_total
  - pattern : kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, topic=(.+)><>Count
    name: kafka_$1_$2_$3_total
    labels:
      topic: "$4"
    type: COUNTER
  - pattern : kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, topic=(.+), partition=(.+)><>Count
    name: kafka_$1_$2_$3_total
    labels:
      topic: "$4"
      partition: "$5"
    type: COUNTER
  - pattern : kafka.(\w+)<type=(.+), name=(.+)><>(Count|Value)
    name: kafka_$1_$2_$3_$4
    type: COUNTER
  - pattern : kafka.(\w+)<type=(.+), name=(.+), (\w+)=(.+)><>(Count|Value)
    name: kafka_$1_$2_$3_$6
    labels:
      "$4": "$5"
```
Java verbose logs
```log
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor83 0x00000001000f5c28]
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor82 0x00000001000f6028]
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor80 0x00000001000f6828]
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor79 0x00000001000f6c28]
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor78 0x00000001000f7028]
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor12 0x00000001000e1c28]
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor11 0x00000001000e1828]
jmx_exporter_1   | [Unloading class sun.reflect.GeneratedSerializationConstructorAccessor5 0x00000001000e0028]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor107 from __JVM_DefineClass__]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor108 from __JVM_DefineClass__]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor109 from __JVM_DefineClass__]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor110 from __JVM_DefineClass__]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor111 from __JVM_DefineClass__]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor112 from __JVM_DefineClass__]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor113 from __JVM_DefineClass__]
jmx_exporter_1   | [Loaded sun.reflect.GeneratedSerializationConstructorAccessor114 from __JVM_DefineClass__]
```

## Update 1 (7/3/2017)

Thanks @eedugon for your input.
I was able to pull more useful logs and it turns out the connection works fine.
I added `java.util.logging.config.file` flag to the `command` in my compose file as follows

```yml
command: java -Djava.util.logging.config.file=/opt/jmx_exporter/logging.properties -jar /opt/jmx_exporter/jmx_exporter.jar 5556 /opt/jmx_exporter/config.yml
```

and mounted the following `logging.properties` file

```properties
handlers = java.util.logging.ConsoleHandler
.level = INFO
java.util.logging.ConsoleHandler.level=FINEST
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

javax.management.level=FINEST
javax.management.remote.level=FINEST
```

This allowed me to get these logs

```sh
jmx_exporter_1   | Jul 03, 2017 3:22:58 PM RMIConnector getMBeanInfo
jmx_exporter_1   | FINEST: name=kafka.log:type=Log,name=LogStartOffset,topic=testing-topic,partition=220
jmx_exporter_1   | Jul 03, 2017 3:22:58 PM RMIConnector getAttribute
jmx_exporter_1   | FINEST: name=kafka.log:type=Log,name=LogStartOffset,topic=testing-topic,partition=220, attribute=Value
```

The above logs get repeated over and over for every topic partition.
We have about 600 partitions on our kafka cluster which makes the endpoint spend a very long time fetching every mbean attributes for each of the kafka partitions (30 minutes so far and still no http response). The most notable mbean namespaces I see in the logs are `kafka.server`, `kafka.log`, and `kafka.cluster`; each of which span each kafka partition. I also noticed that we're making two requests per metric, `getMBeanInfo` and `getAttribute`.

In attempt to calculate the complexity of this request, let me introduce some variable names
```
R: Number of requests per metric (2)
P: Number of partitions (600)
N: Number of namespaces (3)
M: Number of metrics (unknown)
```

The total number of RMI requests `t` would be

```
t = R * P * N * M
t = 2 * 600 * 3 * M
t = 3600 * M
```

Correct if I'm wrong in my calculation above, but this is A LOT of processing for one HTTP request. If `M = 10`, we're talking about 36k RMI requests!

Is there any way to filter which attributes we fetch from JMX? 
Alternatively, can I aggregate partition metrics?
