### ISSUE TITLE
JMX exporter works for weblogic only gather JVM metrics no welogic's

### ISSUE THREAD

**Issue by Keleir** [prometheus/jmx_exporter#160]
After I installed weblogic with `java -jar wls1036_generic.jar`,

I add a line into  `wlserver_10.3/server/bin/startNodeManager.sh` for metrics gathering:
```
JAVA_OPTIONS="$JAVA_OPTIONS -javaagent:/opt/Oracle/monitor/jmx_prometheus_javaagent-0.9.jar=9102:/opt/Oracle/monitor/weblogic.yml"
```
Then I boot weblogic with `startNodeManager.sh` successfully and can glimpse metrics via http://localhost:9102/metrics , but unfortunately it only contains JVM metrics info, none of weblogic.

I doubt that the `weblogic.yml` is not matched, it looks like this:

```
---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "com.bea:Name=*,Type=ServerRuntime"
  - "com.bea:ServerRuntime=*,Type=ApplicationRuntime,*"
  - "com.bea:ServerRuntime=*,Type=JDBCOracleDataSourceRuntime,*"
  - "com.bea:ServerRuntime=*,Type=JMSDestinationRuntime,*"
  - "com.bea:ServerRuntime=*,Type=SAFRemoteEndpointRuntime,*"
  - "com.bea:ServerRuntime=*,Type=ThreadPoolRuntime,*"

rules:
  - pattern: "^com.bea<ServerRuntime=.+, Name=(.+), Type=JDBCOracleDataSourceRuntime><>(.+): (Running|Suspended|Shutdown|Overloaded|Unknown)$"
    attrNameSnakeCase: true
    name: weblogic_datasource_$2
    value: 1
    labels:
      name: $1
      state: $3

  - pattern: "^com.bea<ServerRuntime=.+, Name=(.+), Type=JDBCOracleDataSourceRuntime><>(.+):"
    attrNameSnakeCase: true
    name: weblogic_datasource_$2
    labels:
      name: $1

  - pattern: "^com.bea<ServerRuntime=.+, Name=(.+), Type=JMSDestinationRuntime, JMSServerRuntime=.+><>(.+):"
    attrNameSnakeCase: true
    name: weblogic_messaging_$2
    labels:
      destination: $1

  - pattern: "^com.bea<ServerRuntime=.+, Name=(.+), Type=SAFRemoteEndpointRuntime><>(.+):"
    attrNameSnakeCase: true
    name: weblogic_messaging_$2
    labels:
      endpoint: $1

  - pattern: "^com.bea<ServerRuntime=.+, Name=ThreadPoolRuntime, Type=ThreadPoolRuntime><>(.+):"
    attrNameSnakeCase: true
    name: weblogic_threadpool_$1

  - pattern: "^com.bea<ServerRuntime=.+, Name=(.+), Type=ApplicationRuntime><HealthStateJMX>(.+): HEALTH_(.+)"
    attrNameSnakeCase: true
    name: weblogic_application_$2
    value: 1
    labels:
      name: $1
      state: $3

  - pattern: "^com.bea<Name=.+, Type=ServerRuntime><HealthStateJMX>(.+): HEALTH_(.+)"
    attrNameSnakeCase: true
    name: weblogic_server_$1
    value: 1
    labels:
      state: $2

  - pattern: "^com.bea<Name=.+, Type=ServerRuntime><>(.+): ([A-Z_]+)$"
    attrNameSnakeCase: true
    name: weblogic_server_$1
    value: 1
    labels:
      state: $2
```
BTW, This file is a copy of @cfrantsen pasted on a issue.

Here is the metrics I gathered: [weblogic_metrics.txt](https://github.com/prometheus/jmx_exporter/files/1116885/weblogic_metrics.txt)

Hope to reply, Thanks!
