### ISSUE TITLE
how to define "availability" metrics based on non-numeric values

### ISSUE THREAD

**Issue by jmazzitelli** [prometheus/jmx_exporter#200]
JBoss EAP/WildFly has a "status" attribute on all deployments (as documented here: https://wildscribe.github.io/WildFly/11.0/deployment/index.html )

```
The current runtime status of a deployment.
Possible status modes are OK, FAILED, and STOPPED.
FAILED indicates a dependency is missing or a service could not start.
STOPPED indicates that the deployment was not enabled or was manually stopped.
```

The "status" attribute is on the JMX MBean "jboss.as:deployment=the-name-of-my-app.war"

Because "status" is non-numeric (whose value is either OK, FAILED, or STOPPED), how can jmx-exporter convert this to a numeric Prometheus metric that maps to a metric named "deployment_available"? A sufficient range of metric values would simply be 0 or 1  (0 meaning the app is not available because its status is either FAILED or STOPPED; 1 meaning the app is available because its deployment status is OK).

The use-case is a simple one - looking at the latest value of this metric, one can determine if an app is currently up or down. Also, looking at the historical value of this metric, one can determine the times which the app was available and when it was down and the percentage of time the app was available.

**Comment by brian-brazil** [comment]
You can use the regex against the attribute value, and then the `value` config option to make it 0/1. This needs two rules.

**Comment by jmazzitelli** [comment]
Oh, OK, so basically you have one rule to match the (FAILED | STOPPED) and one rule to match "OK". Got it.

**Comment by jmazzitelli** [comment]
For completeness, here's how to accomplish this. The following rules do what I want - note you need 4 rules - 2 for simple WAR deployments, 2 for EAR deployments (that contain subdeployments):

```
  - pattern: "^jboss.as<deployment=(.+)><>status: OK"
    attrNameSnakeCase: true
    name: wildfly_deployment_availability
    value: 1
    type: GAUGE
    labels:
      name: $1

  - pattern: "^jboss.as<deployment=(.+)><>status: (FAILED|STOPPED)"
    attrNameSnakeCase: true
    name: wildfly_deployment_availability
    value: 0
    type: GAUGE
    labels:
      name: $1

  - pattern: "^jboss.as<deployment=(.+), subdeployment=(.+)><>status: OK"
    attrNameSnakeCase: true
    name: wildfly_deployment_availability
    value: 1
    type: GAUGE
    labels:
      name: $1
      subdeployment: $2

  - pattern: "^jboss.as<deployment=(.+), subdeployment=(.+)><>status: (FAILED|STOPPED)"
    attrNameSnakeCase: true
    name: wildfly_deployment_availability
    value: 0
    type: GAUGE
    labels:
      name: $1
      subdeployment: $2
```

This results in the following metrics (I have a few test deployments in my WildFly):

```
# HELP wildfly_deployment_availability The current runtime status of a deployment. Possible status modes are OK, FAILED, and STOPPED. FAILED indicates a dependency is missing or a service could not start. STOPPED indicates that the deployment was not enabled or was manually stopped. (jboss.as<deployment=kitchensink-ear.ear><>status)
# TYPE wildfly_deployment_availability gauge
wildfly_deployment_availability{name="kitchensink-ear.ear",} 1.0
wildfly_deployment_availability{name="test-little-1.0.0.ear",} 1.0
wildfly_deployment_availability{name="test-simple-1.0.0.war",} 0.0
```
