### ISSUE TITLE
Prometheus Error

### ISSUE THREAD

**Issue by alirajabi** [prometheus/jmx_exporter#203]
Hi, I have 3 cassandra nodes and jmx_export version 0.1.0

after adding this prometheus config:
```yaml
  - job_name: 'cassandra-jmx'

    static_configs:
      - targets: ['192.168.1.1:7070', '192.168.1.2:7070', '192.168.1.3:7070']
``` 

Prometheus gets this error every second
```
Error on ingesting samples with different value but same timestamp
```

my jmx_exporter config:
```
---
lowercaseOutputLabelNames: true
lowercaseOutputName: true
rules:
  - pattern: org.apache.cassandra.metrics<type=(Connection|Streaming), scope=(\S*), name=(\S*)><>(Count|Value)
    name: cassandra_$1_$3
    labels:
      address: "$2"
  - pattern: org.apache.cassandra.metrics<type=(\S*)(?:, ((?!scope)\S*)=(\S*))?(?:, scope=(\S*))?, name=(\S*)><>(Count|Value)
    name: cassandra_$1_$5
    labels:
      "$1": "$4"
      "$2": "$3"
```

please help me how to fix this issue?
