### ISSUE TITLE
Pattern not working

### ISSUE THREAD

**Issue by moreiramarti** [prometheus/jmx_exporter#234]
Hello,

I'm using jmx_exporter 0.2.0 and I try to get a string mbean like this : 

```
- pattern: 'com.eileo.message.services<service=message, type=status, name=applicationStatus><>ServiceStatus: (.*)'
  name: com_eileo_app_servicestatus
  labels:
    state: "$1"
  help: Message ServiceStatus
  type: GAUGE
  value: 1
```

This is my mbean : 
JmxScraper - scrape: 'com.eileo.message.services{service=message, name=applicationStatus, type=status}ServiceStatus': UP

I can't figure why It's not working.

Thank you for your help,
Martinho MOREIRA

**Comment by brian-brazil** [comment]
That should work, in what way is it not working?

**Comment by moreiramarti** [comment]
When I check the metrics page I don't see my metric.
Same config with regular tomcat mbean works fine.
It should be related with my app.

I will update you if I find something.

**Comment by moreiramarti** [comment]
It works with this pattern:
rules:
- pattern: ".*com.eileo.*<.*>.*(ServiceStatus|Version): (.*)"
  value: 1
  type: GAUGE
  labels:
    state: "$2"
  name: com_eileo_app_$1

Don't know why it's not working with the other conf.

Thanks anyway

**Comment by brian-brazil** [comment]
Likely the pattern wasn't quite right. If you look at the HELP of the output metric you'll see what it's matching against.

**Comment by moreiramarti** [comment]
That's what I did here is the help seems the same : 
# HELP com_eileo_app_servicestatus serviceStatus (com.eileo.message.services<service=message, name=applicationStatus, type=status><>ServiceStatus)

**Comment by brian-brazil** [comment]
You had the name and type the wrong way around.

**Comment by sscaling** [comment]
Not to be stupid, but

mbean:
```
com.eileo.message.services<service=message, name=applicationStatus, type=status><>ServiceStatus
```

pattern:
```
com.eileo.message.services<service=message, type=status, name=applicationStatus><>ServiceStatus: (.*)
```

the regex doesn't match

**Comment by sscaling** [comment]
what @brian-brazil said ^^

**Comment by moreiramarti** [comment]
Ok my bad I was so focused about not getting metrics that I didn't looked at the order of the properties.
Sorry again

**Comment by brian-brazil** [comment]
No problem.

**Comment by balboah** [comment]
I'm also struggling to understand what it's matching against.
Examples I tried:

### A
Match against
```
# HELP ClusterStatus_control_staging_kafka_replicator_PartitionGauge Attribute exposed for management (ClusterStatus< cluster=control-staging-kafka-replicator, resourceName=OtherFooBar><>PartitionGauge)
```

with 
```
- pattern: ClusterStatus_control_(.+)_kafka_replicator_(\w+)Gauge .+resourceName=(\w+)
      name: kafka_replicator_controller_$2
      labels:
        cluster: "$1"
        topic: "$3"
      type: GAUGE
```

### B
Match against
```
FINE: scrape: 'ClusterStatus{ cluster=control-staging-test-kafka-replicator, resourceName=_schemas}PartitionGauge': 1
```

with 
```
- pattern: ClusterStatus\{.+cluster=(.+),.+resourceName=(\w+)\}(.+)Gauge
      name: kafka_replicator_controller_$3
      labels:
        cluster: "$1"
        topic: "$2"
      type: GAUGE
```

#

In both configurations, I get no metrics but "jmx*". If I leave a wildcard I get the metrics but with unknown types. For example:
```
# HELP ClusterStatus_control_staging_kafka_replicator_PartitionGauge Attribute exposed for management (ClusterStatus< cluster=control-staging-kafka-replicator, resourceName=OtherFooBar><>PartitionGauge)
# TYPE ClusterStatus_control_staging_kafka_replicator_PartitionGauge untyped
ClusterStatus_control_staging_kafka_replicator_PartitionGauge{resourceName="Foobar",} 1.0
```
