### ISSUE TITLE
kafka-0-8-2.yml is edited 10 months ago, did it work now for Kafka 1.0

### ISSUE THREAD

**Issue by nullne** [prometheus/jmx_exporter#237]
I am preparing to use this YAML config [kafka-0-8-2.yml](https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-0-8-2.yml) for kafka 1.0, I am not sure whether it works or how to check that with latest kafka version .

thank you very much

**Comment by afalko** [comment]
I've been using it for kafka-1.0 and kafka-trunk with my dashboards. I haven't done a full-metric-by-metric comparison though; all the important stuff is there.

**Comment by nullne** [comment]
@afalko nice, and I am checking all metrics now. I found an confusing rule: kafka.cluster 
I didn't found this metics in kafka official documents.

**Comment by C45p31** [comment]
trying to use it also for kafka-connect, but without success:
- pattern : kafka.server<type=(.+), name=(.+)><>(Count|Value)
  name: kafka_server_$1_$2

- pattern : kafka.connect<type=(.+)><>Value
  name: kafka_connect_$1
  
- pattern : kafka.connect<type=(.+), client-id=(.+)><>Value
  name: kafka_connect_$1_2
  
- pattern : kafka.connect<type=(.+), connector=(.+)><>Value
  name: kafka_connect_$1_$2

- pattern : kafka.connect<type=(.+), connector=(.+), task=(.+)><>Value
  name: kafka_connect_$1_$2
  labels:
    task: "$3"
- pattern : kafka.connect<type=(.+), client-id=(.+), node-id=(.+)><>Value
  name: kafka_connect_$1_$2
  labels:
    clientId: "$2"
    nodeId: "$3"

- pattern : kafka.consumer<type=(.+), client-id=(.+)><>Value
  name: kafka_connect_$1_$2

- pattern : kafka.consumer<type=(.+), client-id=(.+), node-id=(.+)><>Value
  name: kafka_connect_$1_$2
  labels:
    clientId: "$2"
    nodeId: "$3"

- pattern : kafka.producer<type=(.+), client-id=(.+)><>Value
  name: kafka_connect_$1_$2
  
- pattern : kafka.producer<type=(.+), client-id=(.+), node-id=(.+)><>Value
  name: kafka_connect_$1_$2
  labels:
    clientId: "$2"
    nodeId: "$3"

- pattern : kafka.producer<type=(.+), client-id=(.+), topic=(.+)><>Value
  name: kafka_connect_$1_$2
  labels:
    clientId: "$2"
    topic: "$3"

Can you tell me what am I doing wrong?

**Comment by jrask** [comment]
I have the following problem running the 0-8-2 version with kafka 1.0.
I would assume that clientId would be one of my clients but seems to the the Thread name instead.
``
kafka_server_fetcherlagmetrics_consumerlag{clientId="ReplicaFetcherThread-0-4",partition="0",topic="in.ft.metrics.anly",} 0.0
``
This is the same for ALL clientId labels.

**Comment by jrask** [comment]
A little deeper dive into the config, it seems that most stuff does not work. I.e, to get the byterate/sec, you would have to change it into something like this.

```
- pattern : kafka.server<type=(.+), name=(.+), topic=(.+)><>OneMinuteRate
  name: kafka_server_$1_$2
  labels:
    topic: "$3"
```
Giving you something like this

```
kafka_server_brokertopicmetrics_bytesoutpersec{topic="__consumer_offsets",} 130.0661851997627
kafka_server_brokertopicmetrics_bytesinpersec{topic="__consumer_offsets",} 120.9578258024825

```

I am new to prometheus and jmx_exporter so I am not familiar with the exact format. I am currently using jmxtrans + influxdb but I am considering to switch to prometheus instead. However, I was hoping that this would not even be an issue.

**Comment by nullne** [comment]
@jrask  Could you share your latest config file for jmx exporter?  0.8.2 seems too old

**Comment by jrask** [comment]
@nullne I have not changed anything from 0.8.2 config and it works for me at the moment. However, I am currently only looking at bytes and messages in and out so there may be other stuff that is not correct. Will take a look at that later.

**Comment by jrask** [comment]
@nullne  I have started to add kafka consumer metrics and the following config works with kafka 1.1 (probably earlier versions as well). I am only picking the metrics I want. 
This should work with consumers like kafka-connect, logstash or any system kafka java clients.

 ```
# 
# sample result
  # kafka_consumer_fetch_manager_metrics_bytes_consumed_total{client_id="some_client-0",topic="some_topic",} 62818.0
  # kafka_consumer_fetch_manager_metrics_records_consumed_total{client_id="some_client-0",topic="some_topic",} 137.0
  #
  - pattern: kafka.consumer<type=(.+), client-id=(.+), topic=(.+)><>(bytes-consumed-total|records-consumed-total)
    name: kafka_$1_$4
    labels:
      client-id: $2
      topic: $3
    type: COUNTER


  #
  # kafka_consumer_fetch_manager_metrics_records_lag_max{client_id="some_client-0",} 0.0
  # 
  - pattern: kafka.consumer<type=(.+), client-id=(.+)><>(records-lag-max)
    name: kafka_$1_$3
    labels:
      client-id: $2
```
