### ISSUE TITLE
Exposing Kafka's "Histograms"

### ISSUE THREAD

**Issue by ankon** [prometheus/jmx_exporter#300]
Kafka has a couple of "Histogram" metrics, such as this one: 
![screen-kafka-histogram-metric](https://user-images.githubusercontent.com/1210641/43639628-28747658-971d-11e8-9aca-05d945a9d88c.png)

With the example kafka-0-8-2.yml the only thing exported for these is the "Count" field:
~~~~
# HELP kafka_controller_controllereventmanager_eventqueuetimems Attribute exposed for management (kafka.controller<type=ControllerEventManager, name=EventQueueTimeMs><>Count)
# TYPE kafka_controller_controllereventmanager_eventqueuetimems untyped
kafka_controller_controllereventmanager_eventqueuetimems 9.0
~~~~

This was quite misleading (the name of the metric seems to indicate "ms", but the value is actually a count of how often kafka observed that event).

What do you think about also exposing the quantiles:
```yml
- pattern : kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile
  name: kafka_$1_$2_$3
  labels:
    "quantile": "0.$4"
```

Generally, as there is a couple of odd metrics for Kafka, what would be the best process to update the default configuration? PR with all changes, or single issues?
