### ISSUE TITLE
Matching patterns... Tomcat 7.x vs Tomcat 8.5

### ISSUE THREAD

**Issue by jogulin** [prometheus/jmx_exporter#337]
It appears that the matching is done by converting the bean to a string and performing a regex match against it.  Looking at the whole thing I would sooner expect it to match as if it were looking at a series of attributes.

From Tomcat 7.0.x:

Using the JMX exporter in a command line debug type situation produces this:

```
$ java -cp jmx_prometheus_javaagent-0.3.1.jar io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper "service:jmx:rmi:///jndi/rmi://localhost:6969/jmxrmi" | grep -i session | grep -i active
Catalina{type=Manager, context=/, host=localhost}[]maxActiveSessions: -1
Catalina{type=Manager, context=/, host=localhost}[]activeSessions: 0
```

From Tomcat 8.5.x:

```
$ java -cp jmx_prometheus_javaagent-0.3.1.jar io.prometheus.jmx.shaded.io.prometheus.jmx.JmxScraper "service:jmx:rmi:///jndi/rmi://localhost:6969/jmxrmi" | grep -i session | grep -i active
Catalina{type=Manager, host=localhost, context=/}[]maxActiveSessions: -1
Catalina{type=Manager, host=localhost, context=/}[]activeSessions: 0
```

Yes... it turns out the order of the matching params in the tomcat_exporter.yml file makes a difference.

The default one from the tomcat exporter site has:

```
 - pattern: 'Catalina<type=Manager, host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), context=([-a-zA-Z0-9+/$%~_-|!.]*)><>(processingTime|sessionCounter|rejectedSessions|expiredSessions|activeSessions):'
   name: tomcat_session_$3_total
   labels:
     context: "$2"
     host: "$1"
   help: Tomcat session $3 total
   type: COUNTER
```
which I modified to include "activeSessions" by adding one more item to the last pattern group, and for Tomcat 8.5.x:

```
# HELP tomcat_session_activesessions_total Tomcat session activeSessions total
# TYPE tomcat_session_activesessions_total counter
tomcat_session_activesessions_total{context="/",host="localhost",} 0.0
```
but in Tomcat 7.0.x it produces nothing.  Adding the same "activeSessions" and reordering the matching patterns thusly:

```
- pattern: 'Catalina<type=Manager, context=([-a-zA-Z0-9+/$%~_-|!.]*), host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|])><>(processingTime|sessionCounter|rejectedSessions|expiredSessions|activeSessions):'
  name: tomcat_session_$3_total
  labels:
    context: "$1"
    host: "$2"
  help: Tomcat session $3 total
  type: COUNTER
```

now produces:

```
# HELP tomcat_session_activesessions_total Tomcat session activeSessions total
# TYPE tomcat_session_activesessions_total counter
tomcat_session_activesessions_total{context="/",host="localhost",} 0.0
```

The fastest "fix" for this is to be sure you check the pattern matches against your currently running version of Tomcat and adjust them as necessary.  I would hope that at some point the exporter itself would be able to handle this without having to assign different pattern matches based on the Tomcat version.
