### ISSUE TITLE
Option to merge metrics by name

### ISSUE THREAD

**Issue by alkalinecoffee** [prometheus/jmx_exporter#374]
Would it be possible to support the merging of metrics by name?

Currently, given the nature of how beans are parsed individually, it looks like we are left to create separate metrics, ie:

```
jmx_cassandra_releaseversion{releaseversion="2.0.2"} 1.0
jmx_cassandra_clustername{clustername="cluster0"} 1.0
```

Is it possible today to merge these two labels into a single metric?

The use-case would be for when users wish to merge more informational values like those above into a single metric to avoid duplication (similar to other `*_build_info` metrics) like:

```
node_exporter_build_info{branch="HEAD", goversion="go1.9.2", revision="98bc64930d34878b84a0f87dfe6e1a6da61e532d", version="0.15.2"} 1.0
prometheus_build_info{branch="HEAD", goversion="go1.11.5", revision="62e591f928ddf6b3468308b7ac1de1c63aa7fcf3", version="2.7.1"}
```

Wondering if something like this would work:

```
- pattern: org.apache.cassandra.db.*(ClusterName)(?::) (.*)
  name: jmx_cassandra
  value: 1.0
  merge_labels: true
  labels:
    "$1": "$2"

- pattern: org.apache.cassandra.db.*(ReleaseVersion)(?::) (.*)
  name: jmx_cassandra
  value: 1.0
  merge_labels: true
  labels:
    "$1": "$2"
```

Which would ideally output:

```
jmx_cassandra{clustername="cluster0", releaseversion="2.0.2"} 1.0
```
