### ISSUE TITLE
Option(s) to rewrite bean attribute values

### ISSUE THREAD

**Issue by benjaminbillet** [prometheus/jmx_exporter#390]
Hello,

I'm currently facing an issue with Kafka Connect metrics. Some beans have a "status" attribute for representing the state of connectors and tasks. 

This attribute is, unfortunately, a String ('unassigned', 'running', 'paused', 'failed', or 'destroyed') which cannot be exported by the JMX Exporter, as I can see here:

https://github.com/prometheus/jmx_exporter/blob/6a8d92c580b93d62a1a9183cbb7cb1a3b19a8473/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L392

Do you plan to have an option to rewrite values of some mbeans attribute? For instance, the configuration would allow to re-map the string value to an integer value, in order to export it as a gauge.

I understand this is quite a specific use-case. Would you accept a PR for this?

Best regards

**Comment by brian-brazil** [comment]
https://www.robustperception.io/converting-string-states-to-booleans-with-the-jmx-exporter

**Comment by benjaminbillet** [comment]
Hello,

It looks interesting, but if I'm not mistaken "Attributes that aren't matched aren't collected". Does it means that all the other attributes will not be exported?

Best regards

**Comment by benjaminbillet** [comment]
Ok, one solution consists into adding an empty rule at the end.

Thanks!

```yaml
rules:
 - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.*), task=(.*)><>status: unassigned'
   name: kafka_connect_connector_task_metrics_status
   value: 0
   type: GAUGE
   labels:
     connector: "$1"
     task: "$2"
 - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.*), task=(.*)><>status: running'
   name: kafka_connect_connector_task_metrics_status
   value: 1
   type: GAUGE
   labels:
     connector: "$1"
     task: "$2"
 - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.*), task=(.*)><>status: paused'
   name: kafka_connect_connector_task_metrics_status
   value: 2
   type: GAUGE
   labels:
     connector: "$1"
     task: "$2"
 - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.*), task=(.*)><>status: failed'
   name: kafka_connect_connector_task_metrics_status
   value: 3
   type: GAUGE
   labels:
     connector: "$1"
     task: "$2"
 - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.*), task=(.*)><>status: destroyed'
   name: kafka_connect_connector_task_metrics_status
   value: 4
   type: GAUGE
   labels:
     connector: "$1"
     task: "$2"
 - match-all: true
```
