### ISSUE TITLE
How to collect more metrics on cassandra "org.apache.cassandra.db:type=StorageService"

### ISSUE THREAD

**Issue by jaibheem** [prometheus/jmx_exporter#398]
Hello,

I tried to collect metrics on cassandra using the below config but I don't see they are being scraped.

Config look like below:

In this case org.apache.cassandra.metrics<type=ClientRequest and org.apache.cassandra.metrics<type=Compaction metrics are scrape but org.apache.cassandra.db<type=StorageService> isn't working. any idea how to collect it? or am I missing anything here?

```
lowercaseOutputName: true
whitelistObjectNames: ["org.apache.cassandra.metrics:*", "org.apache.cassandra.db:*"]
# ColumnFamily is an alias for Table metrics
blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*"]
rules:

- pattern: 'org.apache.cassandra.metrics<type=ClientRequest, scope=(\w*), name=(Latency)><>(Count|Value|75thPercentile|95thPercentile|OneMinuteRate|99thPercentile)'
  name: org.apache.cassandra.metrics.ClientRequest.$2
  labels:
    scope: $1
    unit: $3

- pattern: 'org.apache.cassandra.metrics<type=Compaction, name=(BytesCompacted|PendingTasks|TotalCompactionsCompleted)><>(Value)'
  name: org.apache.cassandra.metrics.Compaction.$1
  labels:
    unit: $2

- pattern: 'org.apache.cassandra.db<type=StorageService>'
  name: org.apache.cassandra.db.StorageService.$1
  labels:
    unit: $2
```
