### ISSUE TITLE
rule pattern implicit widening

### ISSUE THREAD

**Issue by rolandjohann** [prometheus/jmx_exporter#410]
The specified rule pattern are "widened" at runtime resulting in the possibility to match more MBeans than desired and causing to publish duplicate metrics. This can be prevented when the user has the complete control over the regex instead of implicitly match every char before and after the provided pattern.

For example there is following jmx exporter config:
```yaml
rules:
  - pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=\S+, topic=(\S+), partition=(\d+)><>records-lag-max
    name: kafka_consumer_records_lag_max
    type: GAUGE
    labels:
      topic: "$1"
      partition: "$2"

  - pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=\S+, topic=(\S+), partition=(\d+)><>records-lag
    name: kafka_consumer_records_lag
    type: GAUGE
    labels:
      topic: "$1"
      partition: "$2"
```
`records-lag-max` is fine, `records-lag`, too. But there is a bean value `records-lag-avg` that will be matched with the second pattern.

Is there a reason why the user defined pattern will be widened at runtime within the exporter code?

https://github.com/prometheus/jmx_exporter/blob/cae9f262557f4460a3de920fa9542f8ed75f5cbe/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L170

**Comment by brian-brazil** [comment]
Neither of those will match if it wasn't widened, as there's a colon and the value being matched too.

**Comment by rolandjohann** [comment]
You mean that?
https://github.com/prometheus/jmx_exporter/blob/cae9f262557f4460a3de920fa9542f8ed75f5cbe/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L370

Why the bean value will be handled within the match?

**Comment by brian-brazil** [comment]
Yes. So strings can be supported.

**Comment by rolandjohann** [comment]
> So strings can be supported.
What does that mean? As far as I can see the beanValue appended to the regex won't be used anywhere. Please correct me if I'm wrong.

**Comment by brian-brazil** [comment]
This is getting more into usage questions now, and it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by rolandjohann** [comment]
This is more an implementation detail that I would like to discuss and hopefully agree on an implementation that also affects
https://github.com/prometheus/jmx_exporter/pull/161

As I'm able to read and understand the code I think that talking about that topic with mail list users is slightly misleading.

**Comment by rolandjohann** [comment]
In addition, changing the pattern to
```yaml
  - pattern: kafka.consumer<type=consumer-fetch-manager-metrics, client-id=\S+, topic=(\S+), partition=(\d+)><>(\S+)
    name: kafka_consumer_$3
    type: GAUGE
    labels:
      topic: "$1"
      partition: "$2"
```
results in the colon to be part of the metric name
```
# HELP kafka_consumer_records_lag: The latest lag of the partition (kafka.consumer<type=consumer-fetch-manager-metrics, client-id=consumer-26, topic=..., partition=...><>records-lag)
# TYPE kafka_consumer_records_lag: gauge
kafka_consumer_records_lag:{app_name="...",instance="...",job="...",number="...",partition="...",role="executor",topic="..."} 0
```
Workaround for this will be to include the colon, but this is counterintuitive and not documented
