### ISSUE TITLE
How to turn off jvm_threads metrics from the jmx_exporter

### ISSUE THREAD

**Issue by jaibheem** [prometheus/jmx_exporter#417]
Hello,

I am using jmx_exporter to collect metrics from cassandra, and below is the config file

```
lowercaseOutputLabelNames: true
lowercaseOutputName: true
whitelistObjectNames: ["org.apache.cassandra.metrics:*"]
# ColumnFamily is an alias for Table metrics
blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*", "jvm.threads*"]
rules:

- pattern: 'org.apache.cassandra.metrics<type=ClientRequest, scope=(\w*), name=(Latency)><>(Count|Value|75thPercentile|95thPercentile|OneMinuteRate|99thPercentile)'
  name: org.apache.cassandra.metrics.ClientRequest.$2
  labels:
    scope: $1
    unit: $3

- pattern: 'org.apache.cassandra.metrics<type=Compaction, name=(BytesCompacted|PendingTasks|TotalCompactionsCompleted)><>(Value)'
  name: org.apache.cassandra.metrics.Compaction.$1
  labels:
    unit: $2

```

But along with Cassandra metrics I see [extra](https://pastebin.com/5FjqfmQV) metrics from the exporter. I don't need all the metrics, is there a way to turn off these metrics and enable only cassandra metrics?

I tried to blacklist them but it doesn't work
```
blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*", "jvm.threads*"]```

**Comment by brian-brazil** [comment]
There is not, and the various jvm_ metrics are pretty useful for monitoring any JVM.

**Comment by jaibheem** [comment]
Agree, they are useful. but I am using only using jmx_exporter for cassandra metrics and for other common java applications I have other plugins which take care of these. Now all these become redundant, so trying to see if I can disable the jvm metrics from jmx_exporter.

**Comment by brian-brazil** [comment]
The volume of these metrics is nothing compared to the cassandra metrics, I wouldn't worry about it.

**Comment by jaibheem** [comment]
It's not the volume I am concerned about, I am writing two data points for the same metrics for a given VM.

**Comment by brian-brazil** [comment]
It still doesn't cost anything notable, and you can turn off the other one.

**Comment by jaibheem** [comment]
sure, I just trying to see if it's easier to turn off on the jmx_exporter using blacklist options. are you saying it's not possible to turn off? if yes, then I will go with the other route

**Comment by brian-brazil** [comment]
It's not possible to turn off. With Prometheus monitoring a process is meant to provide relevant to that process on one /metrics.

**Comment by matschaffer-roblox** [comment]
Incase it helps anyone I added this to my prometheus operator monitor endpoint definition:

```yaml
metricRelabelings:
- action: drop
  regex: jvm_(memory|threads)_.+
  sourceLabels:
  - __name__
```

Easy enough to re-enable if we decide it's useful but our system's process churn rate means the few extra metrics were turning into 7 million series total over a few hours.
