### ISSUE TITLE
Wrong metric name zookeeper_PacketsSent/zookeeper_PacketsReceived

### ISSUE THREAD

**Issue by freemanlutsk** [prometheus/jmx_exporter#467]
Hello!

I've faced with strange issue, name of those two metrics (zookeeper_PacketsSent/zookeeper_PacketsReceived) contain "MetricName + Value", for e.g.:  **zookeeper_PacketsReceived:_16625546** , should be **zookeeper_PacketsReceived**.

```
# HELP zookeeper_PacketsReceived:_16625546 PacketsReceived (org.apache.ZooKeeperService<name0=ReplicatedServer_id1, name1=replica.1, name2=Follower><>PacketsReceived)
# TYPE zookeeper_PacketsReceived:_16625546 counter
zookeeper_PacketsReceived:_16625546{memberType="Follower",replicaId="1",} 1.6625546E7

# HELP zookeeper_PacketsSent:_17183580 PacketsSent (org.apache.ZooKeeperService<name0=ReplicatedServer_id1, name1=replica.1, name2=Follower><>PacketsSent)
# TYPE zookeeper_PacketsSent:_17183580 counter
zookeeper_PacketsSent:_17183580{memberType="Follower",replicaId="1",} 1.718358E7
```

What am I doing wrong ?
Thank You!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by defreng** [comment]
Hi guys,

I think this is indeed some kind of bug... I'm seeing the same metrics when using the latest Zookeeper example file but can't figure out why the metric value is added in the metric name?

Configuration of that rule:
```
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(Packets.*)"
    name: "zookeeper_$4"
    type: COUNTER
    labels:
      replicaId: "$2"
      memberType: "$3"
```

Resulting metrics:
```
# HELP zookeeper_PacketsReceived:_65976 PacketsReceived (org.apache.ZooKeeperService<name0=ReplicatedServer_id1, name1=replica.1, name2=Follower><>PacketsReceived)
# TYPE zookeeper_PacketsReceived:_65976 counter
zookeeper_PacketsReceived:_65976{memberType="Follower",replicaId="1",} 65976.0
```
