### ISSUE TITLE
Problems with starting JMX exporter 

### ISSUE THREAD

**Issue by Tapa4ik** [prometheus/jmx_exporter#482]
Hello guys! i hava a ZooKeeper and Kafka cluster.
So i have script to run the ZooKeeper instance, and i add the following line as EXTRA_ARGS
`EXTRA_ARGS=${EXTRA_ARGS-'-name kafkaServer -loggc "-javaagent:/opt/jmx-exporter/jmx-exporter.jar=7071:/etc/jmx-exporter/zookeeper.yml"'}`

and when i start my ZooKeeper instance i get the following ERROR message in my log file 
Error: Could not find or load main class "-javaagent:.opt.jmx-exporter.jmx_exporter_javaagent.jar=7071:.etc.jmx-exporter.zookeeper.yml"

here is my zookeeper.yml
```
rules:
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
    name: "zookeeper_$2"
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
    name: "zookeeper_$3"
    labels:
      replicaId: "$2"
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(\\w+)"
    name: "zookeeper_$4"
    labels:
      replicaId: "$2"
      memberType: "$3"
  - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)><>(\\w+)"
    name: "zookeeper_$4_$5"
    labels:
      replicaId: "$2"
      memberType: "$3"

```

P.S i use the https://alex.dzyoba.com/blog/jmx-exporter/ as reference to install and use the JMX_EXPORTER for Monitor Kafka and ZooKeeper status
