### ISSUE TITLE
creating single metric with labels from many MBeans (NOT stopping pattern matching after first occurence)

### ISSUE THREAD

**Issue by piotrrybicki** [prometheus/jmx_exporter#528]
Hi guys!

I'm using kafka (2.X) rules from example_configs, and that works great.
Now, I'd like to add rule to create kafka_info metric.

My rule is:

```
- pattern: kafka.server<type=app-info><>(.*):\W(.*)
  name: kafka_info
  type: GAUGE
  value: 1
  cache: true
  labels:
    "$1": "$2"
```

revelant output from jmx (via jolokia format):

```
kafka.server:type=app-info -- start-time-ms = 1600085451928
kafka.server:type=app-info -- commit-id = c57222ae8cd7866b
kafka.server:type=app-info -- version = 2.4.1
```

query result from promQL using my rule is:

```
kafka_info{commit_id="c57222ae8cd7866b",instance="kafka1.XXX",job="jmx"} | 1
kafka_info{instance="kafka1.XXX",job="jmx",start_time_ms="1600172372814"} | 1
kafka_info{instance="kafka1.XXX",job="jmx",version="2.4.1"} | 1

```

All working as expected, but it would be more convenient, to have all those labels in a single metric, not 3 instances of the same metric.

Is it possible to create jmx_exporter rule definition that will create single metric with all matched labels merged?
Like:

```
kafka_info{instance="kafka1.XXX",job="jmx",version="2.4.1",commit_id="c57222ae8cd7866b"start_time_ms="1600172372814"} | 1
```
