### ISSUE TITLE
how export datasource metrics  ?

### ISSUE THREAD

**Issue by Pascal-be** [prometheus/jmx_exporter#576]
Hi,

I try to export I try many pattern without success
somebody can help me ?
this this the list of patterns than I try :
```
# pattern: 'Catalina<type=DataSource, name="(\w+-\w+)"><>(maxIdle|minIdle|maxWait|active|size|idle|createCount|initialSize|reconnectedCount|maxAge|maxActive|releasedIdleCount|releaseCount):'
# JMX Bean: Catalina:type=DataSource, context=[context name],host=[hostname],class=javax.sql.DataSource,name="[JNDI name]"
#  Catalina:type=DataSource,class=javax.sql.DataSource,name="jdbc/fwk"
#- pattern: 'Catalina<type=DataSource, context="javax.sql.DataSource", host="(\w+)"><>(maxIdle|minIdle|maxWait|active|size|idle|createCount|initialSize|reconnectedCount|maxAge|maxActive|releasedIdleCount|releaseCount):' 
# pattern: 'Catalina<type=DataSource,class=javax.sql.DataSource,host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]),name="(\w+),context=(\w+)"><>(maxIdle|minIdle|maxWait|active|size|idle|createCount|initialSize|reconnectedCount|maxAge|maxActive|releasedIdleCount|releaseCount):' 
# pattern: 'Catalina<type=DataSource, context=(.*),host=(.*),class=javax.sql.DataSource,name="(.*)"><>(maxIdle|minIdle|maxWait|active|size|idle|createCount|initialSize|reconnectedCount|maxAge|maxActive|releasedIdleCount|releaseCount):'
- pattern: 'Catalina<type=DataSource,class=javax.sql.DataSource,name="(.*)"><>(maxIdle|minIdle|maxWait|active|size|idle|createCount|initialSize|reconnectedCount|maxAge|maxActive|releasedIdleCount|releaseCount):'
  name: tomcat_dataSource_$2
  labels:
    name=: $1
  help: Tomcat datasource $1
  type: GAUGE 
```
Thank's, Pascal
