### ISSUE TITLE
How to add  prefix to all metrics?

### ISSUE THREAD

**Issue by cutiechi** [prometheus/jmx_exporter#620]
I want to add prefix to all metrics

**Comment by fstab** [comment]
This can be configured in the Prometheus server, not in the `jmx_exporter`. In the Prometheus server configuration, add `metric_relabel_configs` to the job in your `prometheus.yml`. Example:

```yaml
scrape_configs:
  - job_name: 'jmx_exporter'
    static_configs:
    - targets: ['localhost:8080']
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        target_label: __name__
        regex: '(.*)'
        action: replace
        replacement: my_prefix_${1}
```

This assumes that `jmx_exporter` exports metrics on [http://localhost:8080/metrics](http://localhost:8080/metrics). Without the `metric_relabel_configs` you would see metrics like `jvm_buffer_pool_used_bytes`. With the config, you see them prefixed like `my_prefix_jvm_buffer_pool_used_bytes`. The `regex` and `replacement` give you fine control over which metrics you want to rename how.
