### ISSUE TITLE
Kafka connect, how to expose kafka connector status ?

### ISSUE THREAD

**Issue by ivalexa** [prometheus/jmx_exporter#633]
Hi,

We are using jmx_exporter to export Kafka Connect JMX metrics to Prometheus. In the example config files there:
https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-connect.yml
There is a metric stat that exposes the connector task status:
```
  #kafka.connect:type=connector-task-metrics,connector="{connector}",task="{task}<> status"
  - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.+), task=(.+)><>status: ([a-z-]+)'
    name: kafka_connect_connector_status
    value: 1
    labels:
      connector: "$1"
      task: "$2"
      status: "$3"
    help: "Kafka Connect JMX Connector status"
    type: GAUGE
```
However when the connector fails to start none of the metrics being exposed, in Kafka Connect rest API you can expose connector status that returns connector state:

```
GET /connectors/my-connector/status 
```
https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors-(string-name)-status
`"connector": {
        "state": "RUNNING",
        "worker_id": "fakehost:8083"
    }`

I'm wondering if it's possible to get the same metric from the JMX exporter, looking in confluent official docs(https://docs.confluent.io/home/connect/monitoring.html#connector-metrics), looks like that there is MBean `kafka.connect:type=connector-metrics,connector=”{([-.w]+)` which should export it, can anyone help me with correct pattern to explore it, please, thnx!.
