### ISSUE TITLE
config yml for spring boot metric

### ISSUE THREAD

**Issue by Srsnik** [prometheus/jmx_exporter#657]
Hi,

I am created your spring boot application (2.5.5) with package name: e.g. com.mycompany.myproject, How can I create config yml, when I want to monitor my beans from my package com.mycompany.myproject?

I tried config.yml:
```
startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["com.mycompany.myproject:*"]
rules:
  - pattern: 'com.mycompany.myproject<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: test_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "TEST metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: false
```

I start spring boot application:
```
java -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3614 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -javaagent:jmx_prometheus_javaagent-0.16.1.jar=8081:config.yml -jar myapplication-1.0-SNAPSHOT.jar --spring.profiles.active=local
```

but in browser I don't see any my bean: localhost:8081/metrics
