### ISSUE TITLE
JMX metrics containing quotes are lost

### ISSUE THREAD

**Issue by tooptoop4** [prometheus/jmx_exporter#689]
I have this config:
```
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
lowercaseOutputName: true
lowercaseOutputLabelNames: true
ssl: false
rules:
- pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+)"
  name: debezium_metrics_$4
  labels:
    plugin: "$1"
    name: "$3"
    context: "$2"
```

jmx values like these are being exposed to prometheus (as expected):
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=QueueRemainingCapacity":81920
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=MiningSessionUserGlobalAreaMemoryInBytes":7595872

**BUT issue is metrics like these were the values contain quotes are not being sent:**
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=CurrentScn":"521761522525"
,"debezium.oracle:type=connector-metrics,context=streaming,server=my-topicoracle,attr=LastEvent":"position: {scn: 6533}, key: {\"ID\" : \"421\", \"CONTRACT_NUMBER\" : \"redac\", \"ATTRIB4\" : null}"
