### ISSUE TITLE
Memory Leak when HEAP_OPTS is not set

### ISSUE THREAD

**Issue by BubbaJoe** [prometheus/jmx_exporter#690]
Seems that when HEAP_OPTS (MAX MEMORY Option Specifically) is not set, the Prometheus thread crashes sometimes.

**Comment by kiuby88** [comment]
Hi @BubbaJoe 

I am running a `jmx-exporter` in K8S. I think I am finding a memory leak because the memory usage trends to up until the container is killed by K8S and it is restarted.
I have checked both dumps of memory, for live and all objects in memory. I have found there are a lot of not live objects waiting to be deleted. 
We will try to set a `HEAP_OPTS` value. 
Just to know, can you elaborate a bit the root cause?
Many thanks

**Comment by fstab** [comment]
If you say you are running the `jmx_exporter`, do you mean you attach it as an agent to an existing VM, or are you running it in standalone mode and monitor your application via remote RMI?

If you are using the agent, it would be good to try the standalone mode instead. That way `jmx_exporter` and the JVM being monitored will be two separate processes, and we could see which process has the memory leak.

**Comment by adberger** [comment]
In our case we are running the docker image of bitnami jmx-exporter as a sidecar in k8s:

configMap
```
apiVersion: v1
kind: ConfigMap
data:
  jmx-prometheus.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
    lowercaseOutputLabelNames: true
    lowercaseOutputName: true
    ssl: false
```

pod
```
apiVersion: v1
kind: Pod
spec:
  containers:
  - image: .../jira-software:8.20.8
    name: jira
    ports:
    - containerPort: 5555
      name: jmx
      protocol: TCP
  - command:
    - java
    - -Xmx400m
    - -XshowSettings:vm
    - -jar
    - jmx_prometheus_httpserver.jar
    - "5556"
    - /opt/jmx-config/jmx-prometheus.yml
    image: .../bitnami/jmx-exporter:0
    imagePullPolicy: Always
    name: jmx
    ports:
    - containerPort: 5556
      name: metrics
      protocol: TCP
    resources:
      limits:
        cpu: 150m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi
    volumeMounts:
    - mountPath: /opt/jmx-config
      name: jmx-config
```

![memory_usage_jmx](https://user-images.githubusercontent.com/43774417/165230294-75e60b8d-341a-43e5-b767-e03f34408971.png)
