### ISSUE TITLE
Domain name in labels (weblogic)

### ISSUE THREAD

**Issue by dargow** [prometheus/jmx_exporter#727]
How can I configure the exporter to get the domain name as a label in every runtime metric?
As I can see, such information is present in JMX objects:
![image](https://user-images.githubusercontent.com/12033844/183878979-41aa9ce6-4c6a-4d33-b0be-876785153876.png)

**Comment by dhoard** [comment]
You should be able use a `pattern` along with `labels` per documentation.

**Comment by Nirzak** [comment]
I also want to know. have used the following pattern regex but didn't work.

```
 - pattern: "^com.bea<Name=(.+),Type=Domain>(.+):"
    name: weblogic_$2
    attrNameSnakeCase: true
    labels:
      domain: $1
```

but it didn't work.

also another thing when we see the jmx mbean we can see the mbean is like as the following,
com.bea:Name=name,Type=Domain

but in jmx config we have to mention it like as below format
com.bea<Name=name,Type=Domain><Metric> 

can someone tell me how can I dump or see all the means like as the above format so that we can easily create custom configs?
