### ISSUE TITLE
Allow remote connections again when running in agent mode

### ISSUE THREAD

**Issue by eidottermihi** [prometheus/jmx_exporter#730]
The change in #675 breaks my use case (=case 4 as discussed in #673 ), where ActiveMQ Artemis is monitored via Java Agent but **with** specified jmxUrl or hostPort.

Since 0.17.0 this is no longer possible: 

`SEVERE [io.prometheus.jmx.JmxCollector] Configuration error: When running jmx_exporter as a Java agent, you must not configure 'jmxUrl' or 'hostPort' because you don't want to monitor a remote JVM.`

ActiveMQ Artemis uses a `management.xml` by default, which restricts access to certain MBeans (see https://activemq.apache.org/components/artemis/documentation/latest/management ).
Therefore, it **is necessary to connect "remotely" via JMX to be able to provide a username and password**, altough running in agent mode:

```yml
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi
username: aUsername
password: aPassword
```

I had to downgrade to 0.16.1 to still be able to monitor ActiveMQ Artemis.
