### ISSUE TITLE
is jmx_exporter can monitor SpringBoot tomcat

### ISSUE THREAD

**Issue by zmdstr** [prometheus/jmx_exporter#748]
My dependencecies are

Spring Boot v2.2.2.RELEASE, Spring v5.2.2.RELEASE

I use jmx_exporter with idea，config like this:
-javaagent:./jmx_exporter/jmx_prometheus_javaagent-0.17.2.jar=8080:.config.yaml

the config.yaml is
```yaml
lowercaseOutputName: true
whitelistObjectNames: ["java.lang:type=OperatingSystem", "Catalina:*"]
blacklistObjectNames: []
rules:
  - pattern: 'Catalina<type=Server><>serverInfo: (.+)'
    name: tomcat_serverinfo
    value: 1
    labels:
      serverInfo: "$1"
    type: COUNTER
  - pattern: 'Catalina<type=GlobalRequestProcessor, name=\"(\w+-\w+)-(\d+)\"><>(\w+):'
    name: tomcat_$3_total
    labels:
      port: "$2"
      protocol: "$1"
    help: Tomcat global $3
    type: COUNTER
  - pattern: 'Catalina<j2eeType=Servlet, WebModule=//([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), name=([-a-zA-Z0-9+/$%~_-|!.]*), J2EEApplication=none, J2EEServer=none><>(requestCount|processingTime|errorCount):'
    name: tomcat_servlet_$3_total
    labels:
      module: "$1"
      servlet: "$2"
    help: Tomcat servlet $3 total
    type: COUNTER
  - pattern: 'Catalina<type=ThreadPool, name="(\w+-\w+)-(\d+)"><>(currentThreadCount|currentThreadsBusy|keepAliveCount|connectionCount|acceptCount|acceptorThreadCount|pollerThreadCount|maxThreads|minSpareThreads):'
    name: tomcat_threadpool_$3
    labels:
      port: "$2"
      protocol: "$1"
    help: Tomcat threadpool $3
    type: GAUGE
  - pattern: 'Catalina<type=Manager, host=([-a-zA-Z0-9+&@#/%?=~_|!:.,;]*[-a-zA-Z0-9+&@#/%=~_|]), context=([-a-zA-Z0-9+/$%~_-|!.]*)><>(processingTime|sessionCounter|rejectedSessions|expiredSessions):'
    name: tomcat_session_$3_total
    labels:
      context: "$2"
      host: "$1"
    help: Tomcat session $3 total
    type: COUNTER
```
when I started my application,then to get metrics by curl 'http://localhost:8080/metrics',only get  some jvm_ metrics,there is no tomcat related metrics.
```
# HELP jmx_config_reload_failure_total Number of times configuration have failed to be reloaded.
# TYPE jmx_config_reload_failure_total counter
jmx_config_reload_failure_total 0.0
# HELP jvm_gc_collection_seconds Time spent in a given JVM garbage collector in seconds.
# TYPE jvm_gc_collection_seconds summary
jvm_gc_collection_seconds_count{gc="PS Scavenge",} 22.0
jvm_gc_collection_seconds_sum{gc="PS Scavenge",} 0.361
jvm_gc_collection_seconds_count{gc="PS MarkSweep",} 4.0
jvm_gc_collection_seconds_sum{gc="PS MarkSweep",} 0.612
# HELP jvm_memory_pool_allocated_bytes_total Total bytes allocated in a given JVM memory pool. Only updated after GC, not continuously.
# TYPE jvm_memory_pool_allocated_bytes_total counter
jvm_memory_pool_allocated_bytes_total{pool="Code Cache",} 2.133568E7
jvm_memory_pool_allocated_bytes_total{pool="PS Eden Space",} 4.494152648E9
jvm_memory_pool_allocated_bytes_total{pool="PS Old Gen",} 9.358544E7
jvm_memory_pool_allocated_bytes_total{pool="PS Survivor Space",} 7.3217952E7
jvm_memory_pool_allocated_bytes_total{pool="Compressed Class Space",} 1.3005408E7
jvm_memory_pool_allocated_bytes_total{pool="Metaspace",} 1.0232956E8
# HELP jmx_exporter_build_info A metric with a constant '1' value labeled with the version of the JMX exporter.
# TYPE jmx_exporter_build_info gauge
jmx_exporter_build_info{version="0.17.2",name="jmx_prometheus_javaagent",} 1.0
# HELP jvm_classes_currently_loaded The number of classes that are currently loaded in the JVM
# TYPE jvm_classes_currently_loaded gauge
```
Is anything wrong?
If jmx_exporter can't monitor SpringBoot tomcat,how can I do for monitor my SpringBoot tomcat,I really want to monitor the tomcat thread,thanks
