### ISSUE TITLE
Hard filter by MBeans

### ISSUE THREAD

**Issue by zentkhv** [prometheus/jmx_exporter#782]
How can I filter the value on specific MBeans?
For example: 
kafka_server_socket_server_metrics_select_rate{listener="PLAINTEXT",networkProcessor="1",} 3.3342296316214037

To display this value, I used the code from the example
- pattern: ".*"

How can I modify the pattern or configuration file to display only this metric, and not all (I have more than 7k)?

p.s. I'm not good at regular expressions :(

**Comment by dhoard** [comment]
Can you be more specific regarding your filtering requirement?

Are you only wanting data from the Kafka server socket metrics (as you show above)?

If so... try...

```
  - pattern: "kafka.server<type=socket-server-metrics, listener=(.+), networkProcessor=(.+)><>(.+):"
    name: kafka_server_socketservermetrics_$3
    type: GAUGE
    labels:
      listener: "$1"
      network_processor: "$2"
```

**Comment by zentkhv** [comment]
@dhoard, I want to display only ONE metric (wrote this one for an example).
I would also like to keep the naming word for word (how it came out from ".*").
I tried your pattern, it is more general (and of course more correct if you display metrics with similar tags), it outputs MANY relevant metrics, but in my example I would like to display only ONE metric with exactly this name and tags (I plan to add the necessary ones later by analogy, the main thing is to understand the principle).
Thank you for your help! I hope after this description it became clearer.

**Comment by zentkhv** [comment]
@dhoard, I think I'm starting to understand using JConsole:
![image](https://user-images.githubusercontent.com/70746340/226803637-fea62c81-4867-47c8-9b5f-19b5adee2cc5.png)

Still don't understand:
1) how to specify instead in the syntax, for example, listener=(.+) replace ".+" with PLAINTEXT
2) how to refer to a specific attribute (select-rate in the example)
![image](https://user-images.githubusercontent.com/70746340/226803686-ad4ce373-a800-4685-8b9d-3b790340f543.png)

**Comment by dhoard** [comment]
For your scenario try...

```
- pattern: "kafka.server<type=socket-server-metrics, listener=(PLAINTEXT), networkProcessor=(1)><>(.+):"
    name: kafka_server_socketservermetrics_$3
    type: GAUGE
    labels:
      listener: "PLAINTEXT"
      network_processor: "1"
```
