### ISSUE TITLE
not able to create custom rules

### ISSUE THREAD

**Issue by vineethng** [prometheus/jmx_exporter#786]
Is there a tutorial on creating custom configs for scrapping the metrics.

**Comment by dhoard** [comment]
Can you elaborate on the question? Are you talking about "scraping" or exposed format?

**Comment by Polybiaz** [comment]
With the provided config for the activemq monitoring i see a lot of metrics that are not relevant for us.

For example.
I only want to see the following metric in Output:

```
# HELP activemq_queue_dispatch_count Number of messages that has been delivered to consumers, including those not acknowledged (org.apache.activemq<type=Broker, brokerName=localhost, destinationType=Queue, destinationName=demo2-control-email-processor><>DispatchCount)
# TYPE activemq_queue_dispatch_count untyped
activemq_queue_dispatch_count{destination="demo2-control-email-processor",} 0.0
activemq_queue_dispatch_count{destination="demo1-steuern-kundenakte-object-statistic-queue",} 0.0
activemq_queue_dispatch_count{destination="demo1-planung-auftragsbuchung-gesamtmittel-statistic-queue",} 0.0
```

If i add the following rule, all of the metrics are gone, expect the jvm metrics

```
rules:
- pattern: org.apache.activemq<type=Broker, brokerName=(\S*), destinationType=Queue, destinationName=(\S*)><>DispatchCount
  name: activemq_queue_dispatch_count
  attrNameSnakeCase: true
  labels:
    destination: $2
```

What am I doing wrong?
