### ISSUE TITLE
No value present for param 'schemaRegistry.url'

### ISSUE THREAD

**Issue by dani** [prometheus/jmx_exporter#833]
Just upgraded to 0.22, and jikkou invocation fails with
```
Error: No value present for param 'schemaRegistry.url' (Comma-separated list of URLs for schema registry instances that can be used to register or look up schemas.)
```

I'm invoking it as this
```
jikkou config set-context exchange --config-file=/local/jikkou.conf
jikkou config view --name exchange

echo "Create and modify topics"
jikkou update \
  --selector="kind IN (KafkaTopic,KafkaTopicList)" \
  --files=/local/kafka-topics.yml
```

With jikkou.conf describing how to connect to kafka
```
jikkou {
  kafka {
    client {
      bootstrap.servers = "10.118.7.21:19092,10.118.7.22:19092,10.118.7.23:19092"
      security.protocol = "SSL"
      ssl.keystore.location = "/secrets/jikkou.p12"
      ssl.keystore.type = "PKCS12"
      ssl.keystore.password = "password"
      ssl.truststore.location = "/secrets/jikkou.ca.pem"
      ssl.truststore.type = "PEM"
      client.id = "exchange-jikkou"
      client.dns.lookup = "use_all_dns_ips"
    }
  }
}
```

And kafka-tropics.yml describing my topics
```
apiVersion: kafka.jikkou.io/v1beta2
kind: KafkaTopicList
items:
  - metadata:
      name: main
    spec:
      partitions: 12
      replicas: 3
      configMapRefs: [ TopicDefaultConfig ]

  - metadata:
      name: main-error
    spec:
      partitions: 12
      replicas: 3
      configMapRefs: [ TopicDefaultConfig ]
[...]
---
apiVersion: "core.jikkou.io/v1beta2"
kind: ConfigMap
metadata:
  name: 'TopicDefaultConfig'
data:
  min.insync.replicas: 2
  cleanup.policy: delete
  compression.type: zstd
  retention.ms: 604800000
```
