### ISSUE TITLE
0.19.0 does it support SSL for between JMX Server and Prometheus Server

### ISSUE THREAD

**Issue by Janardhan78** [prometheus/jmx_exporter#867]
i am trying to use 0.19.0 trying to setup SSL connection between prometheus server( scraping from JMX server)  and JMX server , i tried to setup the configuration currently , but it seems that the below configuration doesnt setup SSL between prometheus server and JMX Server ,  is the below configuration applicable for SSL connection between JMX server and application exposing JMX metrics?

```
httpServer:
  ssl:
    certificate:
    alias: localhost
  keyStore:
    filename: localhost.pkcs12
    password: changeit
```

**Comment by dhoard** [comment]
Yes.

Configuration for Prometheus -> (via SSL + basic authentication) -> the JMX exporter:

```
httpServer:
  ssl:
    keyStore:
      filename: localhost.jks
      password: changeit
    certificate:
      alias: localhost
  authentication:
    basic:
      username: Prometheus
      password: secret
```

If are running the `jmx_prometheus_httpserver` jar as a standalone application (not recommended) and want that connection from the JMX exporter to your application to use SSL, you have to add additional configuration:

```
ssl: true
```

and add the following system properties:

```
-Djavax.net.ssl.keyStore=/home/user/.keystore
-Djavax.net.ssl.keyStorePassword=changeit
-Djavax.net.ssl.trustStore=/home/user/.truststore
-Djavax.net.ssl.trustStorePassword=changeit
```

The integration test suite has a lot of examples of various configuration scenarios:

https://github.com/prometheus/jmx_exporter/tree/main/integration_test_suite/integration_tests/src/test/resources/io/prometheus/jmx/test
