### ISSUE TITLE
Add support for default values of regex match groups in rules

### ISSUE THREAD

**Issue by EconomicTouristsArmLate** [prometheus/jmx_exporter#905]
For properly consuming some metrics, i need to set a default value on a label.
This label value is defined by an optional match group, example config:
```
---
lowercaseOutputLabelNames: true
lowercaseOutputName: true
whitelistObjectNames: ["java.lang:type=OperatingSystem", "Catalina:*"]
blacklistObjectNames: []
rules:
  - pattern: 'Catalina<j2eeType=WebModule, name=//(?:localhost/)?([-a-zA-Z0-9+&@/%?=~_|!:.,;]*[-a-zA-Z0-9+&@/%=~_|])(?:##(.+))?, J2EEApplication=none, J2EEServer=none><>startTime:'
    name: tomcat_module_started_at
    labels:
      module: "$1"
      version: "$2"
    help: Tomcat WebModule startTime (unix time)
    type: GAUGE
```

Note that version is fed by an optional regex match.
I'd love to be able to write something along the lines of
```
    labels:
      module: "$1"
      version: "${2:-unversioned}"
```
though I don't care much about the specific syntax (using bash syntax here, which is also commonly used in ENV substitions, eg in docker compose files).

**Comment by dhoard** [comment]
@EconomicTouristsArmLate I believe I understand what you are trying to accomplish, but don't fully follow the use case.

The MBean should be providing a label. Is there a reason that a lack of a label (i.e. empty string) can't be handled downstream?

**Comment by EconomicTouristsArmLate** [comment]
The problem I'm trying to solve is dumb: I need to sort versions via string comparison (this is how tomcat determines the latest / active version of an app). And an empty label value does sort higher than any other value, but it should sort lowest.

This use case is ridiculous due to decisions in other projects, but I'm sure there are other use cases that for a default label value, even if it's just to improve readibility of metrics by providing a default label value.

For now I workaround this with multiple, more specific match rules, but this is quite cumbersome and error prone:

```yaml
rules:
  # first rule with only matches `name` with a version, second rule matches without. only first match is used.
  # this is, so that we always have a value in the version label, so that we can string sort by this, in order to find the latest version
  # in the same way tomcat does... the default version string must thus be sorted before numbers, '-' does that.
  - pattern: 'Catalina<j2eeType=WebModule, name=//(?:localhost/)?([-a-zA-Z0-9+&@/%?=~_|!:.,;]*[-a-zA-Z0-9+&@/%=~_|])(?:##(.+)), J2EEApplication=none, J2EEServer=none><>startTime:'
    name: tomcat_module_started_at
    labels:
      module: "$1"
      version: "$2"
    help: Tomcat WebModule startTime (unix time)
    type: GAUGE
  - pattern: 'Catalina<j2eeType=WebModule, name=//(?:localhost/)?([-a-zA-Z0-9+&@/%?=~_|!:.,;]*[-a-zA-Z0-9+&@/%=~_|]), J2EEApplication=none, J2EEServer=none><>startTime:'
    name: tomcat_module_started_at
    labels:
      module: "$1"
      version: '-'          # ← ← ← ← ← ←  note the default value here
    help: Tomcat WebModule startTime (unix time)
    type: GAUGE
```

**Comment by iplay88keys** [comment]
We would also benefit from this. We currently have this for multiple different Kafka metrics where `user`, `client-id`, or both can be set:

```
    - pattern: 'kafka.server<type=(Request), user=(.+), client-id=(.+)><>request-time: ([1-9][0-9]*|0+\.[1-9]+[0-9]*)'
      name: jmx_kafka_server_request_time
      type: GAUGE
      value: $4
      labels:
        type: $1
        user: $2
        client_id: $3
        kafka_cluster: <%= kafka_cluster %>
    - pattern: 'kafka.server<type=(Request), user=(.+)><>request-time: ([1-9][0-9]*|0+\.[1-9]+[0-9]*)'
      name: jmx_kafka_server_request_time
      type: GAUGE
      value: $3
      labels:
        type: $1
        user: $2
        client_id: "_unknown"
        kafka_cluster: <%= kafka_cluster %>
    - pattern: 'kafka.server<type=(Request), client-id=(.+)><>request-time: ([1-9][0-9]*|0+\.[1-9]+[0-9]*)'
      name: jmx_kafka_server_request_time
      type: GAUGE
      value: $3
      labels:
        type: $1
        user: "_unknown"
        client_id: $2
        kafka_cluster: <%= kafka_cluster %>
```
