### ISSUE TITLE
Ability to use lowercaseOutputName in particular rules

### ISSUE THREAD

**Issue by Nirzak** [prometheus/jmx_exporter#945]
Hi, we know that we can define lowercaseOutputName globally which reflects all the rules. but If we want to define lowercaseOutputName only for particular rules except others then it doesn't work. Currently, we can define attrNameSnakeCase on the rules section but not lowercaseOutputName. The ability to use this option in the rule section will help us a lot. Thanks

**Comment by dhoard** [comment]
The current code either..

1. uses the attribute name as defined by an MBean
2. converts the attribute name to snake case

I looked at the code...

https://github.com/prometheus/jmx_exporter/blob/4d775bcf5083f26c329183e8758a243d304d33dc/collector/src/main/java/io/prometheus/jmx/JmxCollector.java#L556-L560

... and adding a rule configuration value of `attrNameLowercase`  would result in confusing configuration.

Example:

```
rules:
  - pattern: 'org.apache.cassandra.metrics<type=(\w+), name=(\w+)><>Value: (\d+)'
    name: cassandra_$1_$2
    value: $3
    valueFactor: 0.001
    labels: {}
    help: "Cassandra metric $1 $2"
    cache: false
    type: GAUGE
    attrNameSnakeCase: true
    attrNameLowercase: true
```

Is the attribute name snake case? lower case?
Is the user expecting a specific order of operations? (snake case then lowercase?

This _feels_ like a workaround for inconsistent configuration of exporter rules and dashboards.
