### ISSUE TITLE
jmxexporter adding incorrect _total suffix to #HELP  and #TYPE when using COUNTER

### ISSUE THREAD

**Issue by ecerulm** [prometheus/jmx_exporter#968]
I'm using a  jmxrule to convert the `requestCount` from MBean `Catalina:name="http-nio-8033",type=GlobalRequestProcessor` to 
* set metric name to catalina_globalrequestprocessor_requestcount
* give it a help text
* overwrite the labels: 
* set the type to `COUNTER` 

and although the metric name is set to ` catalina_globalrequestprocessor_requestcount` the `# HELP` and `# TYPE` refer to `catalina_globalrequestprocessor_requestcount_total` (note the `_total` suffix at the end).

So the result prometheus text format is 

```
# HELP catalina_globalrequestprocessor_requestcount_total number of requests
# TYPE catalina_globalrequestprocessor_requestcount_total counter
catalina_globalrequestprocessor_requestcount{Application="Tableau",Service="vizqlservice",ServiceInstance="0",} 2829.0
```

As far as I understand this is incorrect since the metric name is actually `catalina_globalrequestprocessor_requestcount` not `catalina_globalrequestprocessor_requestcount_total` . So the generated `# HELP` and `#TYPE` are really for different non-existing metric.

Here is the jmxexporter configuration: 
```
---
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:8750/jmxrmi
lowercaseOutputName: true
includeObjectNames:
  - "java.lang:type=Memory,*"
  # - "tableau.health.jmx:*"
  - "Catalina:type=Manager,*"
  - "Catalina:type=GlobalRequestProcessor,*"
excludeObjectNameAttributes:
  "java.lang:type=Memory":
    - NonHeapMemoryUsage
    - Verbose
    - ObjectPendingFinalizationCount
rules:
  - pattern: 'Catalina<type=GlobalRequestProcessor, name=\"(\w+-\w+)-(\d+)\"><>(\w+)Count:'
    name: catalina_globalrequestprocessor_$3count
    help: number of requests
    labels:
      Application: Tableau
      Service: vizqlservice
      ServiceInstance: '0'
    type: COUNTER
```

If I remove the `type: COUNTER` line then  the prometheus text format generated will be

```
# HELP catalina_globalrequestprocessor_requestcount number of requests
# TYPE catalina_globalrequestprocessor_requestcount untyped
catalina_globalrequestprocessor_requestcount{Application="Tableau",Service="vizqlservice",ServiceInstance="0",} 2848.0
``` 

In this case the metrics name matches in all three lines (no `_total` anywhere) but the `TYPE` is not counter like I wanted it to be.
