### ISSUE TITLE
Metric name "_info" suffix gets trimmed

### ISSUE THREAD

**Issue by iagotomas** [prometheus/jmx_exporter#982]
Hi,
trying to implement a ruleset for some service, running jmx_exporter 1.0.1 as standalone I'm facing a weird issue which I'm not sure I understand. 
I have the following rule for which the "_info" suffix in the name gets dropped. If I employ another suffix or add additional characters to the suffix "_info" it remains. 
```
rules:
  #metrics:name=jvmInfo.runtime.{runtime}.vendor.{vendor}.version.{version},type=gauges
  - pattern: 'metrics<name=jvmInfo\.runtime\.(.+)\.vendor\.(.+)\.version\.(.*), type=gauges><>Value'
    labels:
      runtime: $1
      vendor: $2
      version: $3
    type: UNTYPED
    name: jvm_runtime_info
    help: "JVM info"
```

Resulting metric name:
jvm_runtime{runtime="OpenJDK_Runtime_Environment",vendor="Amazon.com_Inc.",version="17.0.7+7-LTS"} 1.0

Why does "_info" get removed from the name?

**Comment by dhoard** [comment]
The relevant code is here...

https://github.com/prometheus/jmx_exporter/blob/b3823bca97c7fc2166cac7d2d12e95963b352e4b/collector/src/main/java/io/prometheus/jmx/MatchedRule.java#L73

@fstab, do you remember the specifics around why we sanitize the name?

**Comment by dhoard** [comment]
@fstab The code change was introduced as part of metric name collision work.

Do you remember the specifics?
Is it necessary?

**Comment by doxsch** [comment]
We do have the same issue:

Beans:

```
kafka.schema.registry:type=avro-schemas-created
kafka.schema.registry:type=avro-schemas-deleted
kafka.schema.registry:type=json-schemas-created
kafka.schema.registry:type=json-schemas-deleted
kafka.schema.registry:type=protobuf-schemas-created
kafka.schema.registry:type=protobuf-schemas-deleted
```

Rule:
```
rules:
  - pattern: "kafka.schema.registry<type=(.+)-schemas-(.+)>([^:]+):"
    name: "kafka_schema_registry_schemas_$2"
    labels:
      schemaType: $1
```

returned metrics:
```
# HELP kafka_schema_registry_schemas Number of registered Avro schemas kafka.schema.registry:name=null,type=avro-schemas-created,attribute=avro-schemas-created
# TYPE kafka_schema_registry_schemas untyped
kafka_schema_registry_schemas{cluster="e1-kafka-pfnet-lab",schemaType="avro"} 0.0
kafka_schema_registry_schemas{cluster="e1-kafka-pfnet-lab",schemaType="json"} 0.0
kafka_schema_registry_schemas{cluster="e1-kafka-pfnet-lab",schemaType="protobuf"} 0.0

# HELP kafka_schema_registry_schemas_deleted Number of deleted Protobuf schemas kafka.schema.registry:name=null,type=protobuf-schemas-deleted,attribute=protobuf-schemas-deleted
# TYPE kafka_schema_registry_schemas_deleted untyped
kafka_schema_registry_schemas_deleted{cluster="e1-kafka-pfnet-lab",schemaType="avro"} 0.0
kafka_schema_registry_schemas_deleted{cluster="e1-kafka-pfnet-lab",schemaType="json"} 0.0
kafka_schema_registry_schemas_deleted{cluster="e1-kafka-pfnet-lab",schemaType="protobuf"} 0.0
```

The deleted metrics works but the created metric is trimmed.
